Implement well defined window for breakpoint configuration.
WebFreak001/code-debug pull request #313
Opened 2022-03-02 05:59 UTC by brownts

Fixes #307.

The previous implementation worked under the assumption that
breakpoint requests would be received from the client prior to the
debugger having completed it's initialization.  However, if the
debugger completed initialization prior to having received breakpoint
requests from the client, those breakpoints requests would be
ignored (i.e., there was a race condition).  Additionally, the
previous implementation "buffered" the receipt of the breakpoint
requests and would only process them after the debugger initialization
had completed (i.e., "debug-ready").

This change delays the sending of the "initialized" event back to the
client (until the debugger truly has completed its initialization).
As a result, there is no longer a need to buffer the breakpoint
requests.  Breakpoints requests are now forced to be received after
the debugger has been initialized.  Furthermore, a previous change
prevented running the application until after the "configurationDone"
request is received.  Therefore, with this change, there is now a well
defined window (between sending the "initialized" event and receiving
the "configurationDone" request), for breakpoint configuration to
occur.

2022-03-02 12:07 UTC, GitMensch commented
Thank you for this contribution, that looks nice and the defined window is much better than the manual event check.

It looks like you've tested that already on GDB and LLDB, correct?
I currently don't have the second running at all and while I assume "works on one = works on both" this assumption was beaten before...

2022-03-02 14:23 UTC, brownts commented
> Thank you for this contribution, that looks nice and the defined window is much better than the manual event check.
> 
> It looks like you've tested that already on GDB and LLDB, correct? I currently don't have the second running at all and while I assume "works on one = works on both" this assumption was beaten before...

Yes, that is correct.  I ran launch and attach scenarios on both GDB and LLDB, and both seem to operate as expected.

2022-03-02 14:29 UTC, GitMensch commented
Could you do me a favor and try something that takes long to attach?

I'd highly suggest attaching to a process with lots of loaded shared objects (maybe your browser, or something else) and/or attach via SSH to a gdbserver.
Can you add an entry to the Changelog file yourself, please? Otherwise I'd need to do it after the merge.

2022-03-02 14:38 UTC, WebFreak001 requested changes
otherwise I like this change

2022-03-02 14:52 UTC, WebFreak001 commented
actually after reviewing where the event is sent, this seems like it should never work like this?

![Flowchart](https://user-images.githubusercontent.com/2035977/156385524-ca9535ce-fc9f-469b-8c98-6cb4265844b2.png)

If the initialized-event is sent on debug-ready, that should never actually start, as debug-ready is emitted when load/ssh/attach has been run (which in this picture corresponds to the launch request)

2022-03-02 15:11 UTC, brownts commented
Hi @WebFreak001, my interpretation of that flowchart is that the configuration happens asynchronously (per the dashed arrow on the "initialized event") from the primary focus of control in that lifeline.  Therefore, I don't believe there is an implied order between the "launch request" and the breakpoint configuration shown above it.  I think the diagram likely could have been constructed with the "launch request" shown above the breakpoint configuration.

2022-03-02 15:25 UTC, brownts commented
That was my interpretation that there was no ordering dependency there.  That was further emphasized by the wording in the overview which reinforced this understanding:
> Since the development tool does not know when is the correct moment for passing the configuration information to the adapter, the debug adapter is expected to send an [initialized](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized) event to the development tool to announce that it is ready to accept configuration requests. With this approach a debug adapter does not have to implement a buffering strategy for configuration information.

2022-03-02 15:27 UTC, WebFreak001 commented
before that however:

> [...] This configuration information must be passed to the debug adapter before program execution starts. Some debuggers are able to deal with this information very early, even before the debuggee is known; other debuggers accept this information only when the debuggee is about to start running.

2022-03-02 15:40 UTC, brownts commented
> before that however:
> 
> > [...] This configuration information must be passed to the debug adapter before program execution starts. Some debuggers are able to deal with this information very early, even before the debuggee is known; other debuggers accept this information only when the debuggee is about to start running.

Yes, that is correct.  This is accomplished by having the continue/run commands, which are sent to the debugger, gated by having received the configurationDone request (per [here](https://github.com/WebFreak001/code-debug/blob/master/src/mibase.ts#L358)) which guarantees that all breakpoint configuration has occurred prior to program execution starting.

2022-03-02 17:45 UTC, WebFreak001 commented
ok I'd be fine with merging then if you remove the bind(this) and change it to once as per review

2022-03-03 03:03 UTC, brownts commented
> ok I'd be fine with merging then if you remove the bind(this) and change it to `once` as per review

Sounds good, thanks for taking a look at this.  I'll make your suggested changes and push a new update.

2022-03-03 03:41 UTC, brownts commented on src/mibase.ts
> +		this.miDebugger.on("debug-ready", (() => this.sendEvent(new InitializedEvent())).bind(this));
I've now applied these suggestions in the latest push.

2022-03-03 06:55 UTC, merged