prevent error in evaluateRequest when a variable is not found
WebFreak001/code-debug pull request #438
Opened 2024-08-24 21:07 UTC by oltolm

This prevents the error message when a variable can not be found.

2024-09-13 21:59 UTC, GitMensch commented
This should definitely be disabled for 'hover' but the 'watch' context shows the error not in a message box but in the variable "output", no?

2024-09-13 23:31 UTC, oltolm commented
I changed it to only send an error in the `watch` context.

2024-09-14 06:53 UTC, GitMensch requested changes
That's a good direction. 

Please swap the check testing for hover as this makes it more clear that we don't want an error for this case, an additional comment like "suppress error for hover as the user may just play with the mouse" would be good, too.

Add a Changelog entry and that's good for merge.

2024-09-14 11:12 UTC, oltolm commented
Done. Please release a new version. I fixed a severe bug 6 months ago and it is still not in a released version.

2024-09-14 12:16 UTC, merged