Add `registerLimit` config option to specify the registers to list in Registers view
WebFreak001/code-debug pull request #444
Opened 2024-09-18 14:15 UTC by chenzhiy2001

In cases like #421, fetching unfetchable registers can corrupt the whole Registers view. 

So I added `registerLimit` config option to let users specify what registers they want the debugger to automatically fetch, thus avoiding the issue.

2024-09-18 14:46 UTC, GitMensch requested changes
Thank you for this nice PR!

Apart from the comments below:
* please add an entry to the Changelog file
* it is likely reasonable to note this option in the README, as well as pointing out how to get the numbers "(starting from zero)", which I guess is either `info registers` or `interpreter mi2 "-data-list-register-values --skip-unavailable N"`.

2024-09-18 14:46 UTC, GitMensch commented on package.json
> +}
please revert that missing EOL

2024-09-18 14:46 UTC, GitMensch commented on src/backend/mi2/mi2.ts
> +		const result = await this.sendCommand("data-list-register-values N"+ " " +this.registerLimit);
`const result = await this.sendCommand("data-list-register-values N " + this.registerLimit);`
but maybe we should use
`const result = await this.sendCommand("data-list-register-values --skip-unavailable N " + this.registerLimit);`?

2024-09-19 10:06 UTC, GitMensch approved these changes

2024-09-19 10:17 UTC, GitMensch commented
spell check linter failed on "unfetchable", I've asked chatgpt4 for an adjusted text and it changed some other pieces as well, coming up with (after some hinting)

```
There is a Registers view in the VARIABLES view. As we fetch all registers at once, there can be cases where a register that cannot be fetched causes the entire register request to fail, corrupting the entire Registers output. If this happens, you might need to set the `registerLimit` option to specify which registers you want the debugger to fetch automatically.  
For example, to display only registers `rax` and `rip` in an x64 debug session, send the command `-data-list-register-names` in the debug console of an active x64 debug session. You will then receive a response containing an array starting with `["rax","rbx" ...]`. In this array, the index of `rax` is 0 and `rip` is 16, so set the option as `"registerLimit": "0 16"`. If you find the response text hard to navigate, you can paste it into a browser's developer tools console and press enter to get an expandable response object with array elements' indices explicitly displayed.
```

2024-09-19 10:33 UTC, chenzhiy2001 reviewed
- Reverted the deletion of EOL in package.json
- Appended `--skip-unavaliable` after `-data-list-register-names`
- Added an entry in CHANGELOG.md
- Added an introduction of how to set `registerLimit` option in README.md

2024-09-19 10:47 UTC, chenzhiy2001 commented
The introduction paragraph in README.md is being swapped by the new version now.

2024-09-19 12:18 UTC, GitMensch commented
I've run the prettier stuff locally, that's the diff you need to apply:;

```diff

2024-09-19 12:18 UTC, closed without merging

2024-09-19 12:30 UTC, chenzhiy2001 commented
Oops, I forgot to run `npm run prettier-write-docs`. Could you please reopen this pull request so that the correct modification of CHANGELOG.md show up here?

2024-09-19 12:32 UTC, GitMensch commented
I have no clue why the close happened...

2024-09-19 12:34 UTC, chenzhiy2001 commented
> I have no clue why the close happened...

Sometimes Github gets really confusing. I also felt that.